### ISSUE TITLE
[Website] Add Portfolio screen

### ISSUE THREAD

**Issue by nagchanallen** [nagchanallen/investment-tools#13]
# User Story
As a user, I want to see a list of stock transactions that inputted before, at the same time I would be able to create, update and delete the transactions.

# Tasks
- [x] Scaffold Portfolio screen (Protected Screen)
- [ ] Integrate backend API, refer to #12 for the specification
- [ ] Add stock transaction create form using [react-hook-form](https://www.react-hook-form.com/)
- [ ] Add stock transaction table using [AG Grid](https://www.ag-grid.com/) or [React Table](https://tanstack.com/table/v8)
- [ ] Add Delete button on each row of stock transaction table, with confirmation Dialog
- [ ] Add edit modal for stock tranction
