### ISSUE TITLE
[Website] Add Basic Routes and SSO Login with firebase

### ISSUE THREAD

**Issue by nagchanallen** [nagchanallen/investment-tools#4]
## Todos
- [x] Setup routes using `react-router-dom`
- [x] Setup Config and add Config File
- [x] Setup Firebase Web SDK
- [x] Add Firebase UI for SSO Sign in (https://github.com/firebase/firebaseui-web-react)
- [x] Add Sign out feature for Home Page
- [x] Setup Route Guard for Home Page
- [x] Error handling

### Planned Routes
- Root Screen
  - Entry point of website, redirect user to home page or login page base on auth state
- Sign In Screen
  - For unauthenticated user
  - Firebase UI 
  - Google SSO
- Home Screen
  - For authenticated user
  - Sign out button
- Loading Screen
- Error Screen
